apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ncote-web-app
  namespace: ncote-test
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: ncote-test
    server: {{ .Values.spec.destination.server }}
  project: ncote
  source:
    path: ncote-web-app
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}